# Generated by Django 6.0.6 on 2026-07-05 00:23

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(editable=False, help_text='Référence unique du ticket (générée automatiquement)', max_length=20, unique=True, verbose_name='Référence')),
                ('title', models.CharField(help_text='Titre court décrivant le problème', max_length=200, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Titre')),
                ('description', models.TextField(help_text='Description détaillée du problème', verbose_name='Description')),
                ('category', models.CharField(choices=[('HARDWARE', 'Matériel'), ('SOFTWARE', 'Logiciel'), ('NETWORK', 'Réseau'), ('ACCESS', 'Accès'), ('OTHER', 'Autre')], default='OTHER', max_length=20, verbose_name='Catégorie')),
                ('priority', models.CharField(choices=[('LOW', 'Basse'), ('MEDIUM', 'Moyenne'), ('HIGH', 'Haute'), ('CRITICAL', 'Critique')], default='MEDIUM', help_text='Niveau de priorité du ticket', max_length=10, verbose_name='Priorité')),
                ('status', models.CharField(choices=[('OPEN', 'Ouvert'), ('IN_PROGRESS', 'En cours'), ('RESOLVED', 'Résolu'), ('CLOSED', 'Fermé')], default='OPEN', help_text='Statut actuel du ticket', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Résolu le')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fermé le')),
                ('sla_due_date', models.DateTimeField(blank=True, help_text='Date limite de résolution selon le SLA', null=True, verbose_name='Date limite SLA')),
                ('response_time', models.DurationField(blank=True, help_text='Temps écoulé avant la première réponse', null=True, verbose_name='Temps de réponse')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Archivé')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Assigné à')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-created_at'],
                'permissions': [('can_assign_tickets', 'Peut assigner des tickets'), ('can_change_status', 'Peut changer le statut'), ('can_archive_tickets', 'Peut archiver des tickets')],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(help_text='Contenu du commentaire', verbose_name='Contenu')),
                ('is_internal', models.BooleanField(default=False, help_text='Commentaire visible uniquement par les techniciens', verbose_name='Interne')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tickets.ticket', verbose_name='Ticket')),
            ],
            options={
                'verbose_name': 'Commentaire',
                'verbose_name_plural': 'Commentaires',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATE', 'Création'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression'), ('STATUS_CHANGE', 'Changement de statut'), ('ASSIGN', 'Assignation'), ('COMMENT', 'Commentaire'), ('VIEW', 'Visualisation')], max_length=20, verbose_name='Action')),
                ('field_name', models.CharField(blank=True, help_text='Nom du champ modifié', max_length=100, verbose_name='Champ')),
                ('old_value', models.TextField(blank=True, verbose_name='Ancienne valeur')),
                ('new_value', models.TextField(blank=True, verbose_name='Nouvelle valeur')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='tickets.ticket', verbose_name='Ticket')),
            ],
            options={
                'verbose_name': "Journal d'audit",
                'verbose_name_plural': "Journaux d'audit",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(max_length=255, upload_to='tickets/%Y/%m/%d/', verbose_name='Fichier')),
                ('filename', models.CharField(max_length=255, verbose_name='Nom du fichier')),
                ('mime_type', models.CharField(max_length=100, verbose_name='Type MIME')),
                ('size', models.PositiveIntegerField(verbose_name='Taille (octets)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploadé le')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploads', to=settings.AUTH_USER_MODEL, verbose_name='Uploadé par')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tickets.ticket', verbose_name='Ticket')),
            ],
            options={
                'verbose_name': 'Pièce jointe',
                'verbose_name_plural': 'Pièces jointes',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status', 'priority'], name='tickets_tic_status_b256f6_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['created_by', 'assigned_to'], name='tickets_tic_created_f761fc_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['created_at'], name='tickets_tic_created_5dd600_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status', 'created_at'], name='tickets_tic_status_8acd21_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['priority', 'status'], name='tickets_tic_priorit_b610d4_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['reference'], name='tickets_tic_referen_61a57c_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['ticket', '-created_at'], name='tickets_aud_ticket__a487aa_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', '-created_at'], name='tickets_aud_user_id_7dd145_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action'], name='tickets_aud_action_96bc08_idx'),
        ),
    ]
