# Generated by Django 6.0.6 on 2026-07-15 20:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='reference',
            field=models.CharField(blank=True, editable=False, help_text='Référence unique du ticket (générée automatiquement)', max_length=20, unique=True, verbose_name='Référence'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('TICKET_CREATED', '📩 Ticket créé'), ('STATUS_CHANGED', '📌 Statut changé'), ('ASSIGNED', '📋 Ticket assigné'), ('COMMENT_ADDED', '💬 Commentaire ajouté'), ('TICKET_RESOLVED', '✅ Ticket résolu'), ('TICKET_CLOSED', '🔒 Ticket fermé')], max_length=20)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('link', models.CharField(blank=True, max_length=200)),
                ('sound', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='tickets.ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
